#gems
plugins: 			  [jekyll-paginate]

# Dependencies
markdown:         redcarpet
comments:         True
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jesal Mistry
tagline:          'Providing food for thought.'
#description:      'Made with ♥ by <a href="https://twitter.com/jesalnmistry" target="_blank">@jesalnmistry</a>.'
description:      'Made with ♥ by <a href="/about">Jesal</a>.'
url:              http://jesalnmistry.github.io
baseurl:          /

paginate: 		  5
paginate_path: 	  "/blog/page:num/"

author:
  name:           Jesal Mistry
  url:            https://twitter.com/jesalnmistry

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jesalnmistry/jesalnmistry.github.io
