# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jesal Mistry
#tagline:          <some tagline>
#description:      <some description>
url:              http://blog.jesalmistry.com
baseurl:          /

author:
  name:           Jesal Mistry
  url:            https://twitter.com/jesalnmistry

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jesalnmistry/jesalnmistry.github.io
